// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbuczbcdjumhgjljlyfg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRidWN6YmNkanVtaGdqbGpseWZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzMDc5NzEsImV4cCI6MjA1NTg4Mzk3MX0.M4MCxhQbQjo5AsTPqtDuJQ5jHR7_om9hrTivqdXyKwE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);